export const CHAT_USER_LOADEDS= 'CHAT_USER_LOADEDS';
export const CHAT_ACTIVATE= 'CHAT_ACTIVATE';
export const CHAT_MESSAGES_NEW= 'CHAT_MESSAGES_NEW';
export const CHAT_MESSAGES_LOAD= 'CHAT_MESSAGES_LOAD';
export const CHAT_SOCKET_START= 'CHAT_SOCKET_START';
export const CHAT_SOCKET_CLOSE= 'CHAT_SOCKET_CLOSE';
export const CHAT_SOCKET_ONLINE= 'CHAT_SOCKET_ONLINE';